# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4757c81895ca30f242815eeea2e52e7ee97e889197b842a82a669783ffe66816cd16794ae4b16a8376eb51c882a6df561f254f059361a0b157e0797b765dce

test:
  secret_key_base: a79ee21c62cb0453968182231172b580775ade89ea949c97fd01f1a71f53e5ec0ade2b505af3b5be24278d6299c92597ac5edf237020b9991f68d2b1e3bf1792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
